pipeline:
  name: Golang
  identifier: Golang
  projectIdentifier: cargurcargurus65110
  orgIdentifier: cargurus651org
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: "build test and run "
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit test
                  identifier: run_unit_test
                  spec:
                    connectorRef: <+input>
                    image: golang:1.21
                    shell: Sh
                    command: |-
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: go build
                  identifier: go_build
                  spec:
                    connectorRef: <+input>
                    image: golang:1.21
                    shell: Sh
                    command: |-
                      go get gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
              - step:
                  name: oawsp
                  identifier: oawsp
                  template:
                    templateRef: owasp
                    versionLabel: v0.1
              - step:
                  name: fortify
                  identifier: fortify
                  template:
                    templateRef: fortify
                    versionLabel: v0.1
            rollbackSteps: []
        variables:
          - name: myStageVar
            type: String
            description: ""
            value: stageVarValue
  description: This pipeline was updated by Harness AI on 2026-01-21 18:34:41 UTC by cargurus-user11@gmail.com.
