pipeline:
  name: Golang
  identifier: Golang
  projectIdentifier: cargurcargurus65110
  orgIdentifier: cargurus651org
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: Fortify Security Tests
        identifier: security_tests
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: fortify_sast
                  name: Fortify SAST
                  type: FortifyOnDemand
                  timeout: 10m
                  spec:
                    config: default
                    mode: orchestration
                    target:
                      type: repository
                      workspace: <+pipeline.stages.security_tests.spec.cloneCodebase>
                      detection: auto
                    tool:
                      app_name: <+pipeline.identifier>
                      release_name: <+pipeline.sequenceId>
                      target_language: go
                    advanced:
                      fail_on_severity: high
                    auth:
                      access_token: <+input>
                    outputVariables:
                      - name: scanResults
              - step:
                  identifier: owasp_zap
                  name: OWASP ZAP Security Scan
                  type: Zap
                  timeout: 10m
                  spec:
                    config: standard
                    mode: orchestration
                    target:
                      type: repository
                      workspace: <+pipeline.stages.security_tests.spec.cloneCodebase>
                      detection: auto
                    advanced:
                      fail_on_severity: high
                    tool:
                      context: /go-app
                      port: 8090
            rollbackSteps: []
    - stage:
        name: "build test and run "
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit test
                  identifier: run_unit_test
                  spec:
                    connectorRef: <+input>
                    image: golang:1.21
                    shell: Sh
                    command: |-
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: go build
                  identifier: go_build
                  spec:
                    connectorRef: <+input>
                    image: golang:1.21
                    shell: Sh
                    command: |-
                      go get gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
            rollbackSteps: []
        variables:
          - name: myStageVar
            type: String
            description: ""
            value: stageVarValue
        when:
          pipelineStatus: Success
          condition: <+pipeline.stages.security_tests.status> == "SUCCESS"
  description: This pipeline was updated by Harness AI on 2026-01-21 18:34:41 UTC by cargurus-user11@gmail.com.
